export const TASKMODEL_CREATE_REQUEST = 'TASKMODEL_CREATE_REQUEST'
export const TASKMODEL_CREATE_SUCCESS = 'TASKMODEL_CREATE_SUCCESS'
export const TASKMODEL_CREATE_FAIL = 'TASKMODEL_CREATE_FAIL'
export const TASKMODEL_CREATE_RESET = 'TASKMODEL_CREATE_RESET'

export const TASKMODEL_LIST_REQUEST = 'TASKMODEL_LIST_REQUEST'
export const TASKMODEL_LIST_SUCCESS = 'TASKMODEL_LIST_SUCCESS'
export const TASKMODEL_LIST_FAIL = 'TASKMODEL_LIST_FAIL'
export const TASKMODEL_LIST_RESET = 'TASKMODEL_LIST_RESET'

export const TASKMODEL_UPDATE_REQUEST = 'TASKMODEL_UPDATE_REQUEST'
export const TASKMODEL_UPDATE_SUCCESS = 'TASKMODEL_UPDATE_SUCCESS'
export const TASKMODEL_UPDATE_FAIL = 'TASKMODEL_UPDATE_FAIL'
export const TASKMODEL_UPDATE_RESET = 'TASKMODEL_UPDATE_RESET'

export const TASKMODEL_DELETE_REQUEST = 'TASKMODEL_DELETE_REQUEST';
export const TASKMODEL_DELETE_SUCCESS = 'TASKMODEL_DELETE_SUCCESS';
export const TASKMODEL_DELETE_FAIL = 'TASKMODEL_DELETE_FAIL';
export const TASKMODEL_DELETE_RESET = 'TASKMODEL_DELETE_RESET';

export const TASKMODEL_DETAILS_REQUEST = 'TASKMODEL_DETAILS_REQUEST'
export const TASKMODEL_DETAILS_SUCCESS = 'TASKMODEL_DETAILS_SUCCESS'
export const TASKMODEL_DETAILS_FAIL = 'TASKMODEL_DETAILS_FAIL'
export const TASKMODEL_DETAILS_RESET = 'TASKMODEL_DETAILS_RESET'
