export const TASKSTATE_CREATE_REQUEST = 'TASKSTATE_CREATE_REQUEST'
export const TASKSTATE_CREATE_SUCCESS = 'TASKSTATE_CREATE_SUCCESS'
export const TASKSTATE_CREATE_FAIL = 'TASKSTATE_CREATE_FAIL'
export const TASKSTATE_CREATE_RESET = 'TASKSTATE_CREATE_RESET'

export const TASKSTATE_LIST_REQUEST = 'TASKSTATE_LIST_REQUEST'
export const TASKSTATE_LIST_SUCCESS = 'TASKSTATE_LIST_SUCCESS'
export const TASKSTATE_LIST_FAIL = 'TASKSTATE_LIST_FAIL'
export const TASKSTATE_LIST_RESET = 'TASKSTATE_LIST_RESET'

export const TASKSTATE_UPDATE_REQUEST = 'TASKSTATE_UPDATE_REQUEST'
export const TASKSTATE_UPDATE_SUCCESS = 'TASKSTATE_UPDATE_SUCCESS'
export const TASKSTATE_UPDATE_FAIL = 'TASKSTATE_UPDATE_FAIL'
export const TASKSTATE_UPDATE_RESET = 'TASKSTATE_UPDATE_RESET'

export const TASKSTATE_DELETE_REQUEST = 'TASKSTATE_DELETE_REQUEST';
export const TASKSTATE_DELETE_SUCCESS = 'TASKSTATE_DELETE_SUCCESS';
export const TASKSTATE_DELETE_FAIL = 'TASKSTATE_DELETE_FAIL';
export const TASKSTATE_DELETE_RESET = 'TASKSTATE_DELETE_RESET';

export const TASKSTATE_DETAILS_REQUEST = 'TASKSTATE_DETAILS_REQUEST'
export const TASKSTATE_DETAILS_SUCCESS = 'TASKSTATE_DETAILS_SUCCESS'
export const TASKSTATE_DETAILS_FAIL = 'TASKSTATE_DETAILS_FAIL'
export const TASKSTATE_DETAILS_RESET = 'TASKSTATE_DETAILS_RESET'
