export const TASKTHEME_CREATE_REQUEST = 'TASKTHEME_CREATE_REQUEST'
export const TASKTHEME_CREATE_SUCCESS = 'TASKTHEME_CREATE_SUCCESS'
export const TASKTHEME_CREATE_FAIL = 'TASKTHEME_CREATE_FAIL'
export const TASKTHEME_CREATE_RESET = 'TASKTHEME_CREATE_RESET'

export const TASKTHEME_LIST_REQUEST = 'TASKTHEME_LIST_REQUEST'
export const TASKTHEME_LIST_SUCCESS = 'TASKTHEME_LIST_SUCCESS'
export const TASKTHEME_LIST_FAIL = 'TASKTHEME_LIST_FAIL'
export const TASKTHEME_LIST_RESET = 'TASKTHEME_LIST_RESET'

export const TASKTHEME_UPDATE_REQUEST = 'TASKTHEME_UPDATE_REQUEST'
export const TASKTHEME_UPDATE_SUCCESS = 'TASKTHEME_UPDATE_SUCCESS'
export const TASKTHEME_UPDATE_FAIL = 'TASKTHEME_UPDATE_FAIL'
export const TASKTHEME_UPDATE_RESET = 'TASKTHEME_UPDATE_RESET'

export const TASKTHEME_DELETE_REQUEST = 'TASKTHEME_DELETE_REQUEST';
export const TASKTHEME_DELETE_SUCCESS = 'TASKTHEME_DELETE_SUCCESS';
export const TASKTHEME_DELETE_FAIL = 'TASKTHEME_DELETE_FAIL';
export const TASKTHEME_DELETE_RESET = 'TASKTHEME_DELETE_RESET';

export const TASKTHEME_DETAILS_REQUEST = 'TASKTHEME_DETAILS_REQUEST'
export const TASKTHEME_DETAILS_SUCCESS = 'TASKTHEME_DETAILS_SUCCESS'
export const TASKTHEME_DETAILS_FAIL = 'TASKTHEME_DETAILS_FAIL'
export const TASKTHEME_DETAILS_RESET = 'TASKTHEME_DETAILS_RESET'
