export const COMPSTATE_CREATE_REQUEST = 'COMPSTATE_CREATE_REQUEST'
export const COMPSTATE_CREATE_SUCCESS = 'COMPSTATE_CREATE_SUCCESS'
export const COMPSTATE_CREATE_FAIL = 'COMPSTATE_CREATE_FAIL'
export const COMPSTATE_CREATE_RESET = 'COMPSTATE_CREATE_RESET'

export const COMPSTATE_LIST_REQUEST = 'COMPSTATE_LIST_REQUEST'
export const COMPSTATE_LIST_SUCCESS = 'COMPSTATE_LIST_SUCCESS'
export const COMPSTATE_LIST_FAIL = 'COMPSTATE_LIST_FAIL'
export const COMPSTATE_LIST_RESET = 'COMPSTATE_LIST_RESET'

export const COMPSTATE_UPDATE_REQUEST = 'COMPSTATE_UPDATE_REQUEST'
export const COMPSTATE_UPDATE_SUCCESS = 'COMPSTATE_UPDATE_SUCCESS'
export const COMPSTATE_UPDATE_FAIL = 'COMPSTATE_UPDATE_FAIL'
export const COMPSTATE_UPDATE_RESET = 'COMPSTATE_UPDATE_RESET'

export const COMPSTATE_DELETE_REQUEST = 'COMPSTATE_DELETE_REQUEST';
export const COMPSTATE_DELETE_SUCCESS = 'COMPSTATE_DELETE_SUCCESS';
export const COMPSTATE_DELETE_FAIL = 'COMPSTATE_DELETE_FAIL';
export const COMPSTATE_DELETE_RESET = 'COMPSTATE_DELETE_RESET';

export const COMPSTATE_DETAILS_REQUEST = 'COMPSTATE_DETAILS_REQUEST'
export const COMPSTATE_DETAILS_SUCCESS = 'COMPSTATE_DETAILS_SUCCESS'
export const COMPSTATE_DETAILS_FAIL = 'COMPSTATE_DETAILS_FAIL'
export const COMPSTATE_DETAILS_RESET = 'COMPSTATE_DETAILS_RESET'
