export const COMPONENTS_CREATE_REQUEST = 'COMPONENTS_CREATE_REQUEST'
export const COMPONENTS_CREATE_SUCCESS = 'COMPONENTS_CREATE_SUCCESS'
export const COMPONENTS_CREATE_FAIL = 'COMPONENTS_CREATE_FAIL'
export const COMPONENTS_CREATE_RESET = 'COMPONENTS_CREATE_RESET'

export const COMPONENTS_LIST_REQUEST = 'COMPONENTS_LIST_REQUEST'
export const COMPONENTS_LIST_SUCCESS = 'COMPONENTS_LIST_SUCCESS'
export const COMPONENTS_LIST_FAIL = 'COMPONENTS_LIST_FAIL'
export const COMPONENTS_LIST_RESET = 'COMPONENTS_LIST_RESET'

export const COMPONENTS_UPDATE_REQUEST = 'COMPONENTS_UPDATE_REQUEST'
export const COMPONENTS_UPDATE_SUCCESS = 'COMPONENTS_UPDATE_SUCCESS'
export const COMPONENTS_UPDATE_FAIL = 'COMPONENTS_UPDATE_FAIL'
export const COMPONENTS_UPDATE_RESET = 'COMPONENTS_UPDATE_RESET'

export const COMPONENTS_DELETE_REQUEST = 'COMPONENTS_DELETE_REQUEST';
export const COMPONENTS_DELETE_SUCCESS = 'COMPONENTS_DELETE_SUCCESS';
export const COMPONENTS_DELETE_FAIL = 'COMPONENTS_DELETE_FAIL';
export const COMPONENTS_DELETE_RESET = 'COMPONENTS_DELETE_RESET';

export const COMPONENTS_DETAILS_REQUEST = 'COMPONENTS_DETAILS_REQUEST'
export const COMPONENTS_DETAILS_SUCCESS = 'COMPONENTS_DETAILS_SUCCESS'
export const COMPONENTS_DETAILS_FAIL = 'COMPONENTS_DETAILS_FAIL'
export const COMPONENTS_DETAILS_RESET = 'COMPONENTS_DETAILS_RESET'
