export const DEPARTEMENT_CREATE_REQUEST = 'DEPARTEMENT_CREATE_REQUEST'
export const DEPARTEMENT_CREATE_SUCCESS = 'DEPARTEMENT_CREATE_SUCCESS'
export const DEPARTEMENT_CREATE_FAIL = 'DEPARTEMENT_CREATE_FAIL'
export const DEPARTEMENT_CREATE_RESET = 'DEPARTEMENT_CREATE_RESET'

export const DEPARTEMENT_LIST_REQUEST = 'DEPARTEMENT_LIST_REQUEST'
export const DEPARTEMENT_LIST_SUCCESS = 'DEPARTEMENT_LIST_SUCCESS'
export const DEPARTEMENT_LIST_FAIL = 'DEPARTEMENT_LIST_FAIL'
export const DEPARTEMENT_LIST_RESET = 'DEPARTEMENT_LIST_RESET'

export const DEPARTEMENT_UPDATE_REQUEST = 'DEPARTEMENT_UPDATE_REQUEST'
export const DEPARTEMENT_UPDATE_SUCCESS = 'DEPARTEMENT_UPDATE_SUCCESS'
export const DEPARTEMENT_UPDATE_FAIL = 'DEPARTEMENT_UPDATE_FAIL'
export const DEPARTEMENT_UPDATE_RESET = 'DEPARTEMENT_UPDATE_RESET'

export const DEPARTEMENT_DELETE_REQUEST = 'DEPARTEMENT_DELETE_REQUEST';
export const DEPARTEMENT_DELETE_SUCCESS = 'DEPARTEMENT_DELETE_SUCCESS';
export const DEPARTEMENT_DELETE_FAIL = 'DEPARTEMENT_DELETE_FAIL';
export const DEPARTEMENT_DELETE_RESET = 'DEPARTEMENT_DELETE_RESET';

export const DEPARTEMENT_DETAILS_REQUEST = 'DEPARTEMENT_DETAILS_REQUEST'
export const DEPARTEMENT_DETAILS_SUCCESS = 'DEPARTEMENT_DETAILS_SUCCESS'
export const DEPARTEMENT_DETAILS_FAIL = 'DEPARTEMENT_DETAILS_FAIL'
export const DEPARTEMENT_DETAILS_RESET = 'DEPARTEMENT_DETAILS_RESET'
