export const SYSTEM_CREATE_REQUEST = 'SYSTEM_CREATE_REQUEST'
export const SYSTEM_CREATE_SUCCESS = 'SYSTEM_CREATE_SUCCESS'
export const SYSTEM_CREATE_FAIL = 'SYSTEM_CREATE_FAIL'
export const SYSTEM_CREATE_RESET = 'SYSTEM_CREATE_RESET'

export const SYSTEM_LIST_REQUEST = 'SYSTEM_LIST_REQUEST'
export const SYSTEM_LIST_SUCCESS = 'SYSTEM_LIST_SUCCESS'
export const SYSTEM_LIST_FAIL = 'SYSTEM_LIST_FAIL'
export const SYSTEM_LIST_RESET = 'SYSTEM_LIST_RESET'

export const SYSTEM_UPDATE_REQUEST = 'SYSTEM_UPDATE_REQUEST'
export const SYSTEM_UPDATE_SUCCESS = 'SYSTEM_UPDATE_SUCCESS'
export const SYSTEM_UPDATE_FAIL = 'SYSTEM_UPDATE_FAIL'
export const SYSTEM_UPDATE_RESET = 'SYSTEM_UPDATE_RESET'

export const SYSTEM_DELETE_REQUEST = 'SYSTEM_DELETE_REQUEST';
export const SYSTEM_DELETE_SUCCESS = 'SYSTEM_DELETE_SUCCESS';
export const SYSTEM_DELETE_FAIL = 'SYSTEM_DELETE_FAIL';
export const SYSTEM_DELETE_RESET = 'SYSTEM_DELETE_RESET';

export const SYSTEM_DETAILS_REQUEST = 'SYSTEM_DETAILS_REQUEST'
export const SYSTEM_DETAILS_SUCCESS = 'SYSTEM_DETAILS_SUCCESS'
export const SYSTEM_DETAILS_FAIL = 'SYSTEM_DETAILS_FAIL'
export const SYSTEM_DETAILS_RESET = 'SYSTEM_DETAILS_RESET'
